// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJGTGimwKGAJl27r-IZFHdU-rtcSnTCVM',
    appId: '1:310923149901:web:709c314ff16f9cb5961204',
    messagingSenderId: '310923149901',
    projectId: 'fash-food-28712',
    authDomain: 'fash-food-28712.firebaseapp.com',
    storageBucket: 'fash-food-28712.firebasestorage.app',
    measurementId: 'G-D2NSNZF23L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz70-e6a9xJgKZD7Wnq59LJgssLj6MYBs',
    appId: '1:310923149901:android:b77a9d29e15abb79961204',
    messagingSenderId: '310923149901',
    projectId: 'fash-food-28712',
    storageBucket: 'fash-food-28712.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACkmfI8LknG1eWB-RDAmPeWN4rsN_ZpQY',
    appId: '1:310923149901:ios:d1471558a93a7b63961204',
    messagingSenderId: '310923149901',
    projectId: 'fash-food-28712',
    storageBucket: 'fash-food-28712.firebasestorage.app',
    iosBundleId: 'com.fastfood.fashFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACkmfI8LknG1eWB-RDAmPeWN4rsN_ZpQY',
    appId: '1:310923149901:ios:d1471558a93a7b63961204',
    messagingSenderId: '310923149901',
    projectId: 'fash-food-28712',
    storageBucket: 'fash-food-28712.firebasestorage.app',
    iosBundleId: 'com.fastfood.fashFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJGTGimwKGAJl27r-IZFHdU-rtcSnTCVM',
    appId: '1:310923149901:web:24918a721580baaf961204',
    messagingSenderId: '310923149901',
    projectId: 'fash-food-28712',
    authDomain: 'fash-food-28712.firebaseapp.com',
    storageBucket: 'fash-food-28712.firebasestorage.app',
    measurementId: 'G-6LK17XKDYB',
  );
}
